environment:
  global:
    PROJECT_NAME: neovim-gtk-win64
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: 1.38.0

install:
#  - ps: Start-FileDownload "https://static.rust-lang.org/dist/channel-rust-stable"
#  - ps: $env:RUST_VERSION = Get-Content channel-rust-stable | select -first 1 | %{$_.split('-')[1]}
  - SET RUST_URL=https://static.rust-lang.org/dist/rust-%RUST_VERSION%-%TARGET%.exe
  - SET PATH=C:\Rust\bin;C:\msys64\mingw64\bin;%PATH%;C:\msys64\usr\bin
  - SET PKG_CONFIG_PATH=C:\msys64\mingw64\lib\pkgconfig
  - ps: Start-FileDownload $env:RUST_URL -FileName rust-dist.exe
  - rust-dist.exe /VERYSILENT /NORESTART /COMPONENTS="Rustc,Gcc,Cargo,Std" /DIR="C:\Rust"
  - rustc -V
  - cargo -V
  - pacman --noconfirm -S mingw-w64-x86_64-gtk3
# for icon
  - pacman --noconfirm -S mingw-w64-x86_64-binutils
  - pacman --noconfirm -S mingw-w64-x86_64-gcc

build_script:
  - cargo test
  - cargo build --release

after_build:
  - cmd: >-
      mkdir dist

      cd dist

      mkdir bin share lib

      mkdir share\glib-2.0 share\icons lib\gdk-pixbuf-2.0

      xcopy .\..\target\release\nvim-gtk.exe .\bin 1> nul

      for %%a in (C:\msys64\mingw64\bin\libfribidi-0.dll,C:\msys64\mingw64\bin\libatk-1.0-0.dll,C:\msys64\mingw64\bin\libbz2-1.dll,C:\msys64\mingw64\bin\libcairo-2.dll,C:\msys64\mingw64\bin\libcairo-gobject-2.dll,C:\msys64\mingw64\bin\libepoxy-0.dll,C:\msys64\mingw64\bin\libexpat-1.dll,C:\msys64\mingw64\bin\libffi-6.dll,C:\msys64\mingw64\bin\libfontconfig-1.dll,C:\msys64\mingw64\bin\libfreetype-6.dll,C:\msys64\mingw64\bin\libgcc_s_seh-1.dll,C:\msys64\mingw64\bin\libgdk-3-0.dll,C:\msys64\mingw64\bin\libgdk_pixbuf-2.0-0.dll,C:\msys64\mingw64\bin\libgio-2.0-0.dll,C:\msys64\mingw64\bin\libglib-2.0-0.dll,C:\msys64\mingw64\bin\libgmodule-2.0-0.dll,C:\msys64\mingw64\bin\libgobject-2.0-0.dll,C:\msys64\mingw64\bin\libgraphite2.dll,C:\msys64\mingw64\bin\libgtk-3-0.dll,C:\msys64\mingw64\bin\libharfbuzz-0.dll,C:\msys64\mingw64\bin\libiconv-2.dll,C:\msys64\mingw64\bin\libintl-8.dll,C:\msys64\mingw64\bin\libpango-1.0-0.dll,C:\msys64\mingw64\bin\libpangocairo-1.0-0.dll,C:\msys64\mingw64\bin\libpangoft2-1.0-0.dll,C:\msys64\mingw64\bin\libpangowin32-1.0-0.dll,C:\msys64\mingw64\bin\libpcre-1.dll,C:\msys64\mingw64\bin\libpixman-1-0.dll,C:\msys64\mingw64\bin\libpng16-16.dll,C:\msys64\mingw64\bin\libstdc++-6.dll,C:\msys64\mingw64\bin\libwinpthread-1.dll,C:\msys64\mingw64\bin\zlib1.dll,C:\msys64\mingw64\bin\libthai-0.dll,C:\msys64\mingw64\bin\libdatrie-1.dll) do xcopy %%a .\bin 1> nul

      xcopy C:\msys64\mingw64\share\glib-2.0 .\share\glib-2.0 /E 1> nul

      xcopy C:\msys64\mingw64\share\icons .\share\icons /E 1> nul

      xcopy C:\msys64\mingw64\lib\gdk-pixbuf-2.0 .\lib\gdk-pixbuf-2.0 /E 1> nul

      cd ..

      7z a nvim-gtk-mingw64.7z dist\*

artifacts:
  - path: nvim-gtk-mingw64.7z
    name: mingw64-bin

test: false
